-- The knowledge base of every identity: data/workide.sqlite
--
-- ONE BASE, TWO KINDS OF FACT. A vacancy is the same posting whoever looks at
-- it: its title, text, link and what was learned about it later (the page
-- read for its description, the link check) live once, in `vacancies`. What
-- depends on who is looking — the score against that identity's CV, the
-- class, the display row, the person's answer and their application — lives
-- in `vacancy_identity`, one row per identity and vacancy. A vacancy one
-- identity fetched is scored for every identity (the owner, 2026-10-05).
--
-- Until 2026-10-05 every identity had a file of its own, and a vacancy two
-- identities both wanted was fetched, read and checked twice.
--
-- Applied by tools/db.py (Python) and by the app's tests (JavaScript), so this
-- file is the single definition of the schema. Every statement is idempotent.
--
-- WHO WRITES WHAT. Each column has exactly one writer, which is what lets the
-- pipeline and the app write at the same time without overwriting each other:
--   vacancies, companies, identities, selections*,
--   vacancy_identity.computed/score/class/duplicate_of/view/views - the pipeline
--   pipeline_runs                                   - the pipeline (tools/runstate.py)
--   vacancy_identity.feedback_* (except feedback_reviewed_at),
--   applied_at and the funnel columns               - the app; `feedback.py reject`,
--                                                     the agent's own "not for me"
--   vacancy_identity.feedback_reviewed_at           - tools/feedback.py
--
-- VERSIONS. 1-7: one file per identity (see git history). 8: one base for
-- every identity — tools/merge_shared_base.py built it from the old files.

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- The identities that have looked at the base. The prefix is the key, the
-- same one that names the identity's folder and files.
CREATE TABLE IF NOT EXISTS identities (
  id           TEXT PRIMARY KEY,
  -- What the search is about, in the identity's own words: its tab's caption.
  display_name TEXT,
  created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vacancies (
  -- common.stable_id(source, external_id): generated by a script, and the same
  -- vacancy fetched again gets the same id, so feedback survives re-fetching.
  id   TEXT PRIMARY KEY,
  -- What the vacancy IS, as JSON: what the source said, when it was first and
  -- last seen, and what was learned later. Nothing identity-specific.
  data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vacancy_identity (
  identity_id           TEXT NOT NULL REFERENCES identities(id),
  vacancy_id            TEXT NOT NULL REFERENCES vacancies(id),
  -- score.score_vacancy() against this identity, as JSON; score and class are
  -- copied out of it for queries and for reading the base by hand.
  computed              TEXT,
  score                 INTEGER,
  class                 TEXT,
  -- The canonical record when this one is a near-duplicate (kb.mark_duplicates):
  -- the canonical one is the best-scored, so it depends on the identity.
  duplicate_of          TEXT,
  -- report.vacancy_view() as JSON: what a row in the app shows. Latest version.
  view                  TEXT,
  -- The same in every language of the app's interface, {"en": {...}, "ru":
  -- {...}} (report.vacancy_views): the app shows the one the person picked.
  -- `view` stays the identity's own language, for the report and feedback.
  views                 TEXT,
  feedback_status       TEXT NOT NULL DEFAULT 'new'
                        CHECK (feedback_status IN ('new', 'applied', 'rejected', 'bugged',
                                                   'expired', 'contacted', 'interview',
                                                   'awaiting_final', 'awaiting_offer',
                                                   'declined', 'offered', 'started')),
  rejected_reason       TEXT,
  bugged_reason         TEXT,
  feedback_at           TEXT,
  -- The application funnel, written by the app (renderer/funnel.js). Comments
  -- on steps that happened are never NULL: '' means the step happened and the
  -- person wrote nothing. The interviews are JSON arrays, one entry each —
  -- their number is the number of interviews; the dates run parallel.
  applied_at            TEXT,
  contact_comment       TEXT,
  contact_at            TEXT,
  interview_comments    TEXT,
  interview_at          TEXT,
  final_comment         TEXT,
  final_at              TEXT,
  awaiting_offer_comment TEXT,
  awaiting_offer_at     TEXT,
  -- The employer's no. NOT the person's "rejected" (not for me) above: that
  -- one judges the vacancy, this one closes an application.
  declined_comment      TEXT,
  declined_at           TEXT,
  offered_comment       TEXT,
  offered_at            TEXT,
  started_comment       TEXT,
  started_at            TEXT,
  -- The selection the person was looking at when they left the feedback.
  feedback_selection_id INTEGER REFERENCES selections(id),
  feedback_reviewed_at  TEXT,
  PRIMARY KEY (identity_id, vacancy_id)
);

CREATE INDEX IF NOT EXISTS vacancy_identity_feedback
  ON vacancy_identity(identity_id, feedback_status, feedback_reviewed_at);

-- Companies are facts too: a company's reputation does not depend on who asks.
CREATE TABLE IF NOT EXISTS companies (
  key  TEXT PRIMARY KEY,
  data TEXT NOT NULL
);

-- A selection is what one run of one identity showed. Selections are only
-- ever added, never changed, so the history of what was shown survives for
-- feedback analysis.
CREATE TABLE IF NOT EXISTS selections (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  identity_id TEXT NOT NULL REFERENCES identities(id),
  run         INTEGER NOT NULL,
  created_at  TEXT NOT NULL,
  -- 'rebuild': re-selected from the stored base without fetching anything.
  kind        TEXT NOT NULL CHECK (kind IN ('run', 'rebuild'))
);

CREATE INDEX IF NOT EXISTS selections_identity ON selections(identity_id, kind, id);

-- The markets of a selection. Copied per selection, because the segment
-- configuration may change between runs.
CREATE TABLE IF NOT EXISTS selection_segments (
  selection_id INTEGER NOT NULL REFERENCES selections(id),
  slug         TEXT NOT NULL,
  name         TEXT NOT NULL,
  position     INTEGER NOT NULL,
  is_default   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (selection_id, slug)
);

-- Selection x market x vacancy. Compact on purpose: this table grows with
-- every run, so the display row lives once in vacancy_identity.view instead.
CREATE TABLE IF NOT EXISTS selection_items (
  selection_id     INTEGER NOT NULL REFERENCES selections(id),
  segment          TEXT NOT NULL,
  vacancy_id       TEXT NOT NULL REFERENCES vacancies(id),
  class            TEXT NOT NULL,
  class_position   INTEGER NOT NULL,
  section_limit    INTEGER NOT NULL,
  score            INTEGER NOT NULL,
  eligibility_rank INTEGER NOT NULL,
  PRIMARY KEY (selection_id, segment, vacancy_id)
);

CREATE INDEX IF NOT EXISTS selection_items_vacancy ON selection_items(vacancy_id);

-- One row per pipeline run: whether one is going right now, and at what stage.
-- A run that dies without its `finally` (killed, power cut) stops beating:
-- readers treat a 'running' row whose heartbeat is older than a threshold as
-- not running, and the next run marks it 'interrupted'. See tools/runstate.py.
-- One run at a time across ALL identities: the base is shared, and a run
-- saves the facts it loaded an hour earlier.
CREATE TABLE IF NOT EXISTS pipeline_runs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  identity_id  TEXT,
  started_at   TEXT NOT NULL,
  heartbeat_at TEXT NOT NULL,
  finished_at  TEXT,
  status       TEXT NOT NULL
               CHECK (status IN ('running', 'finished', 'failed', 'interrupted')),
  stage        TEXT,
  pid          INTEGER,
  host         TEXT,
  log_path     TEXT,
  error        TEXT
);

CREATE INDEX IF NOT EXISTS pipeline_runs_status ON pipeline_runs(status);
