-- The knowledge base of one identity: data/<prefix>/<prefix>.sqlite
--
-- One file per identity, so the identity is the file itself and no table
-- carries an identity key. That keeps one person's vacancies physically apart
-- from another's (see tools/kb.py, "Loading and saving").
--
-- Applied by tools/db.py (Python) and by the app's tests (JavaScript), so this
-- file is the single definition of the schema. Every statement is idempotent.
--
-- WHO WRITES WHAT. Each column has exactly one writer, which is what lets the
-- pipeline and the app write at the same time without overwriting each other:
--   vacancies.data, vacancies.view, companies, selections*   - the pipeline
--   pipeline_runs                                            - the pipeline (tools/runstate.py)
--   vacancies.feedback_* (except feedback_reviewed_at),
--   applied_at and the contact/interview/final columns        - the app
--   vacancies.feedback_reviewed_at                           - tools/feedback.py
--
-- VERSIONS. 1: the first schema. 2: pipeline_runs. 3: feedback status 'expired'
-- (the vacancy was closed or its link dead — not a judgement of the pick).
-- 4: the application funnel — contacted, interview, awaiting_final — with a
-- comment and a date for every step.

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS vacancies (
  -- common.stable_id(source, external_id): generated by a script, and the same
  -- vacancy fetched again gets the same id, so feedback survives re-fetching.
  id                    TEXT PRIMARY KEY,
  -- The whole record as JSON, exactly what vacancies.json used to hold.
  data                  TEXT NOT NULL,
  -- report.vacancy_view() as JSON: what a row in the app shows. Latest version.
  view                  TEXT,
  -- The same in every language of the app's interface, {"en": {...}, "ru":
  -- {...}} (report.vacancy_views): the app shows the one the person picked.
  -- `view` stays the identity's own language, for the report and feedback.
  views                 TEXT,
  feedback_status       TEXT NOT NULL DEFAULT 'new'
                        CHECK (feedback_status IN ('new', 'applied', 'rejected', 'bugged',
                                                   'expired', 'contacted', 'interview',
                                                   'awaiting_final')),
  rejected_reason       TEXT,
  bugged_reason         TEXT,
  feedback_at           TEXT,
  -- The application funnel, written by the app (renderer/funnel.js). Comments
  -- on steps that happened are never NULL: '' means the step happened and the
  -- person wrote nothing. The interviews are JSON arrays, one entry each —
  -- their number is the number of interviews; the dates run parallel.
  applied_at            TEXT,
  contact_comment       TEXT,
  contact_at            TEXT,
  interview_comments    TEXT,
  interview_at          TEXT,
  final_comment         TEXT,
  final_at              TEXT,
  -- The selection the person was looking at when they left the feedback.
  feedback_selection_id INTEGER REFERENCES selections(id),
  feedback_reviewed_at  TEXT
);

CREATE INDEX IF NOT EXISTS vacancies_feedback
  ON vacancies(feedback_status, feedback_reviewed_at);

CREATE TABLE IF NOT EXISTS companies (
  key  TEXT PRIMARY KEY,
  data TEXT NOT NULL
);

-- A selection is what one run showed. Selections are only ever added, never
-- changed, so the history of what was shown survives for feedback analysis.
CREATE TABLE IF NOT EXISTS selections (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  run        INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  -- 'rebuild': re-selected from the stored base without fetching anything.
  kind       TEXT NOT NULL CHECK (kind IN ('run', 'rebuild'))
);

-- The markets of a selection. Copied per selection, because the segment
-- configuration may change between runs.
CREATE TABLE IF NOT EXISTS selection_segments (
  selection_id INTEGER NOT NULL REFERENCES selections(id),
  slug         TEXT NOT NULL,
  name         TEXT NOT NULL,
  position     INTEGER NOT NULL,
  is_default   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (selection_id, slug)
);

-- Selection x market x vacancy. Compact on purpose: this table grows with
-- every run, so the display row lives once in vacancies.view instead.
CREATE TABLE IF NOT EXISTS selection_items (
  selection_id     INTEGER NOT NULL REFERENCES selections(id),
  segment          TEXT NOT NULL,
  vacancy_id       TEXT NOT NULL REFERENCES vacancies(id),
  class            TEXT NOT NULL,
  class_position   INTEGER NOT NULL,
  section_limit    INTEGER NOT NULL,
  score            INTEGER NOT NULL,
  eligibility_rank INTEGER NOT NULL,
  PRIMARY KEY (selection_id, segment, vacancy_id)
);

CREATE INDEX IF NOT EXISTS selection_items_vacancy ON selection_items(vacancy_id);

-- One row per pipeline run: whether one is going right now, and at what stage.
-- A run that dies without its `finally` (killed, power cut) stops beating:
-- readers treat a 'running' row whose heartbeat is older than a threshold as
-- not running, and the next run marks it 'interrupted'. See tools/runstate.py.
CREATE TABLE IF NOT EXISTS pipeline_runs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at   TEXT NOT NULL,
  heartbeat_at TEXT NOT NULL,
  finished_at  TEXT,
  status       TEXT NOT NULL
               CHECK (status IN ('running', 'finished', 'failed', 'interrupted')),
  stage        TEXT,
  pid          INTEGER,
  host         TEXT,
  log_path     TEXT,
  error        TEXT
);

CREATE INDEX IF NOT EXISTS pipeline_runs_status ON pipeline_runs(status);
